BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_mla.yaml
TRAINER_NAME: dagger # dagger, or recollect_trainer
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 8
TENSORBOARD_DIR: data/tensorboard_dirs/mla_nrsub
CHECKPOINT_FOLDER: data/checkpoints/mla_nrsub
EVAL_CKPT_PATH_DIR: data/checkpoints/mla_nrsub
RESULTS_DIR: data/checkpoints/mla_nrsub/evals

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

IL:
  epochs: 45
  batch_size: 8
  lr: 1.5e-4
  use_iw: True
  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_NRSub/{split}/{split}_gt.json.gz

  DAGGER:
    iterations: 1
    update_size: 10819
    p: 1.0
    preload_lmdb_features: False
    lmdb_features_dir: data/trajectories_dirs/mla_nrsub/trajectories.lmdb

MODEL:
  policy_name: MLAPolicy

  INSTRUCTION_ENCODER:
    bidirectional: True
  PROGRESS_MONITOR:
    use: True
    alpha: 1.0
  PEAK_ATTENTION:
    use: True
    alpha: 0.4
    sigma: 0.6
  SEQ2SEQ:
    encoder_prev_action: True
    decoder_prev_action: True
